Remmeauth/remme-core

remme/rest_api/__main__.py, remme/rest_api/batch_status.py, remme/rest_api/certificate.py, remme/rest_api/openapi.yml, remme/rest_api/personal.py, remme/rest_api/token.py, remme/settings.py, remme/token/token_client.py, requirements.txt, setup.py
**TBD**:
* Admin API (validators and on-chain settings)
* Enable/disable methods in API
=> Implement REST API with OpenAPI and Connexion

.gitconfig
* Please install `git-flow` (`brew install git-flow`).
* **UPD**: Run `git config --local include.path ../.gitconfig`
* **UPD**: Run `git flow init -d`
* Follow this tutorial to learn how to use the tool: https://github.com/nvie/gitflow#creating-featurereleasehotfixsupport-branches
* Flow based on https://datasift.github.io/gitflow/IntroducingGitFlow.html with prefixes and naming changed for the sake of simplicity.
=> Share git flow settings

remme/certificate/client.py, remme/rest_api/__main__.py, remme/rest_api/certificate.py, remme/rest_api/certificate_api_decorator.py, remme/rest_api/openapi.yml
https://remmeio.atlassian.net/browse/REM-167
=> Certificate store custom date

remme/rest_api/token.py, remme/rest_api/transaction.py, remme/shared/basic_client.py, remme/tests/test_rest_api.py
https://remmeio.atlassian.net/browse/REM-250
=> Return batch id when sending a transaction request

remme/rest_api/openapi.yml, remme/rest_api/token.py
Returning account address with it's balance.
=> Unpushed changes from the previous PR

remme/certificate/handler.py, remme/rest_api/certificate.py, remme/shared/basic_client.py
fix a mistake in BasicClient.get_value
=> Fix get_value

remme/rest_api/atomic_swap.py
=> GET Swap Info

.env, remme/rest_api/__main__.py
https://remmeio.atlassian.net/browse/REM-274
=> Add CORS specification to rest api

Dockerfile, remme/rest_api/swagger-index.patch
We can now maintain updates to the latest versions of Swagger UI
=> Update to Swagger UI 3.17.0

.env
Allow all urls for dev mode and leave commented production version.
=> Allow all urls for dev purposes

.env, docs/family-account.rst, docs/family-pub-key.rst
Reverts Remmeauth/remme-core#70
=> Revert "Update documentation for `account` and `pub_key` families"

remme/shared/utils.py, remme/tp/atomic_swap.py, requirements.txt, tests/tp/test_atomic_swap.py
Fix to solidity and REMchain hashing algorithm mismatch.
=> Add web3 hashing to atomic swaps

.env, .gitignore, CHANGELOG.md, Dockerfile, README.rst, remme/rest_api/openapi.yml, setup.py
Merge release changes to `dev`
=> Merge release changes to dev

remme/protos/atomic_swap_pb2.py, remme/rest_api/openapi.yml, remme/tp/atomic_swap.py, tests/tp/test_atomic_swap.py
Implements issue REM-445.
https://remmeio.atlassian.net/browse/REM-415
- added is_expired in proto
- catered test cases
- catered openapi
=> add is_expired

Makefile, docker-compose/docs.yml, docs/index.rst, docs/remme-ws.rst
Implements issue REM-438.
- Fix makefile for `restart_dev` cmd;
- Add docs for WS;
=> Documentation of WS

remme/clients/account.py, remme/clients/atomic_swap.py, remme/clients/basic.py, remme/clients/pub_key.py, remme/genesis/__main__.py, remme/tp/account.py, remme/tp/basic.py, remme/tp/pub_key.py, tests/test_helper.py, tests/tp/test_account.py, tests/tp/test_pub_key.py
Implements issue REM-332.
- Add `get_multiple_data` to retrieve protos from addresses in one call;
=> F revise in out

docker-compose/docs.yml, docs/index.rst, docs/rest-api.rst
Implements issue REM-436.
REST-API Documentation
=> Docs: REST-API

Makefile, remme/rest_api/api_handler.py, remme/ws/ws.py
Implements issue REM-471.
- Fix ws notification does not send when status changed;
- Fix error in rest api handling response;
=> Fix ws notifications and rest api response handling

.circleci/config.yml, CHANGELOG.md, Dockerfile, Makefile, README.rst, bash/toml-to-env.py, config/remme-rest-api.toml, docker-compose/base.yml, docker-compose/genesis.yml, genesis.sh, remme/clients/basic.py, remme/genesis/__main__.py, remme/rest_api/__main__.py, remme/rest_api/api_methods_switcher.py, remme/settings/default.py, remme/tp/__main__.py, run.sh, setup.py
=> R 0.5.0 alpha

docs/index.rst, docs/remme-ws-events.rst
=> Documentation for events

remme/clients/basic.py, remme/rest_api/token.py, remme/tp/account.py, tests/test_rest_api.py
Implements issue REM-522.
- Add validation for zero balance;
- Add logic to rest with zero balance and available balance of signer;
=> Zero amount transfer fix

remme/clients/block_info.py, remme/rest_api/api_handler.py, remme/rest_api/block_info.py, remme/rest_api/openapi.yml
=> REM-518: Block info bugs

remme/clients/basic.py, remme/clients/block_info.py, remme/rest_api/block_info.py
=> REM-518: Add 404 error msg for block info

bash/genesis.sh, docker-compose/base.yml, docker-compose/genesis.yml, remme/settings/__init__.py, scripts/token_post.lua
Implements issue REM-523.
- Change sign priv and pub key pathes;
- Update token load script;
=> REM-523: Change sign priv key

remme/shared/utils.py, requirements.txt
=> Move web3 to pysha3

config/remme-log-config.toml, config/remme-rest-api-log-config.toml, config/remme-tp-log-config.toml, docker-compose/base.yml, docker-compose/genesis.yml, docker-compose/test.yml, remme/rest_api/node_key.py, remme/rest_api/validator.py, remme/shared/logging.py, remme/tp/__main__.py
=> Add log conf file

Dockerfile, Makefile, genesis.sh, run.sh
- Fix error when running `run.sh`/`genesis.sh`: `./genesis.sh: line 3: ./bash/network-config.env: No such file or directory`
=> Fix error in run scripts

Dockerfile, Makefile, genesis.sh, run.sh
=> Hf fix run script

remme/clients/atomic_swap.py, remme/clients/basic.py, remme/clients/pub_key.py, tests/test_helper.py, tests/test_rest_api.py
Implements issue REM-556.
- Remove test_helper;
=> REM-556: Remove test helper

docs/family-pub-key.rst
Implements issue REM-439
@ArtemFrantsiian @DeV1doR Please check documentation for `pub_key`.
=> REM-439 Update documentation for transaction processors

docs/rpc-api.rst
=> REM-588: Update rpc doc

Makefile, remme/rpc_api/transaction.py
=> REM-665: Add check for public key

build/docker-compose-release.yml, build/docker-compose.yml, config/sawtooth-validator-config.toml, docker/development.dockerfile, docker/release.dockerfile
Introduce fixes for development testnet
=> F fix not synced

docs/rpc-api.rst, remme/rpc_api/atomic_swap.py, remme/rpc_api/pkc.py
=> REM-582: Fix atomic swap

build/build.sh, scripts/node/validator.sh
* Correct settings for `devmode` consensus;
* Fix for `build.sh` which was always building a production version;
* Make `validator.sh` more verbose.
=> Fixes to #130

remme/clients/block_info.py
=> REM-661: fix block info

.pylintrc, Makefile, docs/conf.py, remme/genesis/__main__.py, remme/rpc_api/__main__.py, remme/tp/__main__.py
- Pylint setup. From now on everyone is obliged to use it and follow when it is rational.
=> Initial pylint configuration

Makefile, docs/rpc-api.rst, remme/clients/basic.py, remme/clients/router.py, remme/rpc_api/__main__.py, remme/rpc_api/atomic_swap.py, remme/rpc_api/base.py, remme/rpc_api/block_info.py, remme/rpc_api/personal.py, remme/rpc_api/pkc.py, remme/rpc_api/state.py, remme/rpc_api/transaction.py, remme/rpc_api/utils.py, remme/shared/exceptions.py, remme/ws/events.py, remme/ws/ws.py
=> REM-703: Wrap rpc error response

README.rst, docs/architecture.rst, docs/conf.py, docs/family-pub-key.rst, docs/index.rst, docs/remme-ws-events.rst
=> REM-751 Fix warning in `make docs`.

remme/ws/events.py
=> REM-755: Fix multipart error

remme/clients/router.py, remme/settings/__init__.py, remme/ws/ws.py
=> REM-753: Add timeout handling for router

docs/rpc-api.rst
=> REM-711: Update docs with status code for RPC

remme/rpc_api/__main__.py, remme/settings/__init__.py, remme/settings/default_log_config.toml, remme/shared/logging_setup.py, remme/ws/events.py
=> REM-601: Move settings loading to app directly

docs/family-atomic-swap.rst, remme/clients/account.py, remme/rpc_api/transaction.py, remme/settings/helper.py, remme/tp/account.py, remme/tp/atomic_swap.py, tests/tp/test_atomic_swap.py
=> REM-738: Add genesis address check for as

remme/tp/pub_key.py
=> REM-824: Catch PEM deserialization error

CHANGELOG.md, docker/compose/bg.yml, docker/compose/restart-always.yml, scripts/run.sh
Automatic restart can be enabled with `RESTART_ALWAYS=1 make run`
=> REM-772 Docker Autorestart

pyproject.toml, remme/clients/pub_key.py, remme/rpc_api/pkc.py, remme/tp/pub_key.py, testing/unit/tp/public_key/base.py, testing/unit/tp/public_key/test_revoke.py, testing/unit/tp/public_key/test_store.py, testing/utils/client.py
=> REM-568 Add signatures support

remme/rpc_api/event/_handlers.py, testing/unit/rpc/events/handlers/test_atomic_swap.py, testing/unit/rpc/events/handlers/test_batch.py, testing/unit/rpc/events/handlers/test_transfer.py
- Ticket (task) — https://remmeio.atlassian.net/browse/REM-928
— Add validation for batch identifier.
- Web sockets interface — https://remmeio.atlassian.net/wiki/spaces/WikiREMME/pages/437190680/2018-11-14+RFC+1+WebSockets+architecture+and+interface
=> REM-928: add validation for events params

remme/rpc_api/transaction.py, remme/shared/router.py, scripts/run.sh
=> REM-495: Add `family_name` filter for transactions

remme/tp/atomic_swap.py, testing/unit/tp/atomic_swap/test_close.py, testing/unit/tp/atomic_swap/test_expire.py, testing/unit/tp/atomic_swap/test_init.py
- Ticket (task) — https://remmeio.atlassian.net/browse/REM-919
— Remove excess transactions in atomic swap process in respect to simple increase and decrease sender and receiver accounts balances.
=> REM-919: remove excess transactions in atomic swap process

remme/clients/account.py, remme/settings/__init__.py, remme/tp/account.py, testing/unit/tp/atomic_swap/test_close.py, testing/unit/tp/atomic_swap/test_expire.py, testing/unit/tp/atomic_swap/test_init.py
- Ticket (task) — https://remmeio.atlassian.net/browse/REM-920
— Genesis owners to zero address owners in cases of fetching address by key.
=> REM-817: genesis owners to zero address owners address key

remme/rpc_api/event/_handlers.py
=> REM-938: Update address handling for transfer event

pyproject.toml, remme/rpc_api/transaction.py, remme/shared/forms/__init__.py, remme/shared/forms/_fields.py, remme/shared/forms/account.py, remme/shared/forms/atomic_swap.py, remme/shared/forms/base.py, remme/shared/forms/pub_key.py, remme/tp/__main__.py, remme/tp/account.py, remme/tp/atomic_swap.py, remme/tp/basic.py, remme/tp/pub_key.py, testing/unit/tp/account/test_genesis.py, testing/unit/tp/account/test_transfer.py, testing/unit/tp/atomic_swap/test_approve.py, testing/unit/tp/atomic_swap/test_close.py, testing/unit/tp/atomic_swap/test_expire.py, testing/unit/tp/atomic_swap/test_init.py, testing/unit/tp/atomic_swap/test_set_lock.py, testing/unit/tp/public_key/test_revoke.py, testing/unit/tp/public_key/test_store.py, testing/utils/client.py
=> REM-905: Add validation for send_raw_transaction method

Jenkinsfile, README.rst, config/log/block-info-tp.toml, config/log/poet-validator-registry.toml, config/log/remme-rpc-api.toml, config/log/remme-tp.toml, config/log/settings-tp.toml, config/log/validator-rest-api.toml, config/log/validator.toml
Implements issue REM-759.
- update status build from Jenkins
- delete CircleCI from repo
- update logs policy to "INFO"
- delete make clean from Jenkinsfile - Multibranch only for test repo
=> REM-759 Update status build

docker/compose/base.yml, docker/sawtooth.dockerfile
Implements issue REM-900.
@Annitra please run all test cases here. We need to  verify that changing the framework version do not break anything.
=> REM-900 Upgrade to stable Sawtooth 1.1

remme/rpc_api/_base.py
=> REM-987: Fix ws send error

remme/settings/__init__.py, remme/settings/helper.py, remme/shared/forms/account.py, remme/tp/account.py, remme/tp/atomic_swap.py, remme/tp/basic.py, remme/tp/context.py, remme/tp/pub_key.py, testing/mocks/stub.py, testing/unit/tp/account/test_transfer.py, testing/unit/tp/atomic_swap/test_expire.py, testing/unit/tp/atomic_swap/test_init.py, testing/unit/tp/public_key/test_store_for_other.py
=> REM-972: Add init implementation for state preloader

config/remme-rpc-api.toml, docker/compose/base.yml, docs/influxdb.rst, pyproject.toml, remme/rpc_api/event/_event.py, remme/settings/default_config.toml, remme/shared/metrics.py, remme/tp/basic.py, utils/execution_time_stats.py
Follow-up of #200 to measure the actual performance change and store measurements in InfluxDB.
**TBD**
=> Metrics collection for core

.gitignore, remme/rpc_api/atomic_swap.py, remme/rpc_api/block_info.py, remme/rpc_api/event/_handlers.py, remme/rpc_api/network.py, remme/rpc_api/personal.py, remme/rpc_api/pkc.py, remme/rpc_api/state.py, remme/rpc_api/transaction.py, remme/rpc_api/utils.py, remme/shared/forms/__init__.py, remme/shared/forms/base.py
=> REM-990: Add validation for all rpc handlers

remme/shared/forms/base.py, remme/shared/forms/pub_key.py, testing/unit/tp/public_key/test_store_for_other.py
=> REM-986: Fix nested serializer

remme/rpc_api/_base.py
Implements issue REM-1024
- add time metrics
- modify some other code in `_handle_rpc_msg` method
=> [REM-1024] Add time metrics for rpc methods.

remme/shared/forms/__init__.py, remme/shared/forms/node_account.py, remme/tp/node_account.py, testing/unit/tp/node_account/shared.py, testing/unit/tp/node_account/test_transfer_from_unfrozne_to_operational.py
- Ticket (task) — https://remmeio.atlassian.net/browse/REM-1108
=> REM-1108: Node account transfer from unfrozen to operational balance

testing/unit/tp/atomic_swap/test_set_lock.py, testing/unit/tp/public_key/base.py, testing/unit/tp/public_key/test_revoke.py, testing/unit/tp/public_key/test_store.py, testing/unit/tp/public_key/test_store_for_other.py
- Ticket (task) — https://remmeio.atlassian.net/browse/REM-1079
=> REM-1079: Parametrize test cases for transaction processing

remme/shared/forms/_fields.py, testing/unit/rpc/test_atomic_swap.py
- Ticket (task) — https://remmeio.atlassian.net/browse/REM-991
=> REM-991: Modify error message for method get_atomic_swap_info

Makefile, config/remme-client-config.toml, docker/release.dockerfile, remme/clients/basic.py, remme/clients/block_info.py, remme/rpc_api/__main__.py, remme/rpc_api/_base.py, remme/settings/default_config.toml, remme/shared/messaging.py, remme/shared/router.py, remme/shared/utils.py, scripts/protogen.sh
=> REM-1018: Change block info votes

config/remme-rpc-api.toml, docs/apis/rpc.rst, remme/clients/node_account.py, remme/genesis/__main__.py, remme/rpc_api/node_account.py, remme/rpc_api/pkc.py, remme/settings/__init__.py, remme/settings/default_config.toml, remme/shared/forms/__init__.py, remme/shared/forms/node_account.py, remme/tp/account.py, remme/tp/node_account.py, scripts/node/validator.sh, testing/unit/tp/node_account/shared.py
=> REM-1240: Add genesis node account creation

Jenkinsfile
- add jenkins-worker for tests of this repository (all branches and PRs)
=> add jenkins-worker

remme/rpc_api/block_info.py, testing/unit/rpc/test_block_info.py
- Ticket (task) — https://remmeio.atlassian.net/browse/REM-1243
=> REM-1243: Fix bug for method list_blocks with parameter address

remme/clients/block_info.py, remme/rpc_api/block_info.py, remme/shared/forms/_validators.py, remme/shared/forms/block_info.py, testing/unit/rpc/test_block_info.py
- First ticket (task) — https://remmeio.atlassian.net/browse/REM-1144
- Second ticket (task) — https://remmeio.atlassian.net/browse/REM-1145
- Third ticket (task) — https://remmeio.atlassian.net/browse/REM-1146
=> REM-1144, REM-1145, REM-1146: Fix bug for method get_blocks with invalid params

remme/rpc_api/block_info.py, remme/shared/forms/_fields.py, remme/shared/forms/identifier.py, testing/unit/rpc/test_block_info.py
- Ticket (task) — https://remmeio.atlassian.net/browse/REM-1135
=> REM-1135: Fix method fetch_block with invalid parameter id

remme/shared/forms/__init__.py, remme/shared/forms/node_account.py, remme/shared/forms/pub_key.py, remme/tp/node_account.py, testing/unit/tp/node_account/test_set_bet_config.py
=> REM-1248: Add set bet handler

remme/tp/__main__.py, remme/tp/account.py, remme/tp/consensus_account.py
=> REM-1251: Add consensus account address generation

remme/rpc_api/state.py, testing/unit/rpc/test_state.py
- Ticket (task) — https://remmeio.atlassian.net/browse/REM-1136
=> REM-1136: Fix method fetch_state with invalid parameter address

remme/rpc_api/transaction.py, testing/unit/rpc/test_transaction.py
- Ticket (task) — https://remmeio.atlassian.net/browse/REM-1134
=> REM-1134: Fix method fetch_batch with invalid parameter batch id

remme/rpc_api/state.py, testing/unit/rpc/test_state.py
- First ticket (task) — https://remmeio.atlassian.net/browse/REM-1155
- Second ticket (task) — https://remmeio.atlassian.net/browse/REM-1156
=> REM-1155, REM-1156: Fix method list_state with invalid parameter address

build/build.sh, docker/compose/base.yml, remme/clients/basic.py, remme/clients/consensus_account.py, remme/clients/node_account.py, remme/genesis/__main__.py, remme/settings/__init__.py, remme/shared/forms/__init__.py, remme/shared/forms/node_account.py, remme/tp/atomic_swap.py, remme/tp/basic.py, remme/tp/consensus_account.py, remme/tp/node_account.py, remme/tp/obligatory_payment.py, scripts/node/validator.sh, testing/unit/tp/consensus_account/shared.py, testing/unit/tp/consensus_account/test_pay_reward.py, testing/unit/tp/node_account/test_close_masternode.py, testing/unit/tp/obligatory_payment/test_obligatory_payment.py
Implements issue REM-1247.
https://github.com/Remmeauth/sawtooth-core/pull/4
https://github.com/Remmeauth/remme-protobuf/pull/25
=> REM-1247: Add pay reward handler

remme/rpc_api/state.py, remme/shared/forms/_validators.py, remme/shared/forms/state.py, remme/shared/utils.py, testing/unit/rpc/test_state.py
- Ticket REM-1157 (task) — https://remmeio.atlassian.net/browse/REM-1157
- Ticket REM-1158 (task) — https://remmeio.atlassian.net/browse/REM-1158
- Ticket REM-1159 (task) — https://remmeio.atlassian.net/browse/REM-1159
- Ticket REM-1160 (task) — https://remmeio.atlassian.net/browse/REM-1160
- Ticket REM-1161 (task) — https://remmeio.atlassian.net/browse/REM-1161
- Ticket REM-1162 (task) — https://remmeio.atlassian.net/browse/REM-1162
- Ticket REM-1163 (task) — https://remmeio.atlassian.net/browse/REM-1163
=> REM-1157, 1158, 1159, 1160, 1161, 1162, 1163 : Fix method list_state with invalid parameters

remme/tp/__main__.py, remme/tp/bet.py, remme/tp/internal.py, remme/tp/node_account.py, scripts/node/validator.sh, testing/unit/tp/node_account/shared.py, testing/unit/tp/node_account/test_do_bet.py, testing/unit/tp/node_account/test_set_bet.py
=> REM-1247: Add do bet system

remme/tp/bet.py
=> REM-1357: Fix bet

remme/settings/__init__.py, remme/tp/consensus_account.py, scripts/node/validator.sh, testing/unit/tp/consensus_account/shared.py, testing/unit/tp/obligatory_payment/shared.py
Implements issue REM-1352.
Removal of settings from batch injector https://github.com/Remmeauth/sawtooth-core/pull/9
=> Clean settings

remme/tp/consensus_account.py, testing/unit/tp/consensus_account/test_pay_reward.py
=> REM-1353: Fix reward percent

scripts/node/validator.sh
Reverts Remmeauth/remme-core#325
=> Revert "REM-1329 Inject bet tx to the end of a block."

config/sawtooth-validator-config.toml, scripts/node/validator.sh
Before the merge, apply this:
https://github.com/Remmeauth/sawtooth-core/pull/12
=> Add fix for scheduler
